name: judge_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  timezone: ^0.10.1
  teledart: ^0.6.1
  dotenv: ^4.2.0
  hive: ^2.2.3
  image: ^4.5.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.5.4
  hive_generator: ^2.0.1